### PR TITLE
Implement further abstraction of the forge-eventbus-dsl

### LINKED ISSUE #1: Furhter abstraction of the Eventbus-DSL.
Currently, the Eventbus-DSL heavily relies on the Forge EventBus. Due to some mods using alternative event buses, for example, a popular choice is https://github.com/KevinPriv/KEventBus it would be easier to abstract the current DSL even further.

We could create an interface that the Forge EventBus and custom event buses can implement to call to register code.

Example:
```kotlin
interface EventBus {
  fun <T> register(event: Class<T>, action: T.() -> Unit) 
}
```

### PR DESCRIPTION
**Pull request by ChachyDev**
Resolves #1

### CODE REVIEW

**Comment by isXander** [comment]
Even though this repository is named `kotlin-forge-api` this PR is trying to expand beyond that. The forge eventbus implementation should be seperate so this DSL can be used outside a 1.8.9 forge environment.

**Comment by ChachyDev** [comment]
What do you mean by that? The DSL should work perfectly fine outside of a 1.8.9 forge environment due to abstraction changes just made...

**Comment by isXander** [comment]
forge-event-dsl/src/main/kotlin/club/chachy/event/impl/forge/ForgeEventBus.kt

**Comment by ChachyDev** [comment]
Yes? That is the default implementation. Without the default implementation, it would quite literally be a mess for developers.

**Comment by ChachyDev** [comment]
Just because the class exists doesn't mean the DSL won't work. It will only fail if you reference ForgeEventBus

**Pull request merged**
